#!/bin/bash

echo "🚀 Deploying GenHealth.AI Assessment API to Render..."
echo ""
echo "📋 Steps to get your public URL:"
echo ""
echo "1. Go to: https://render.com"
echo "2. Sign in with GitHub"
echo "3. Click 'New +' → 'Web Service'"
echo "4. Select repository: NNDSrinivas/GenHealthAI-assesment"
echo "5. Use these EXACT settings:"
echo "   - Name: genhealth-assessment-api"
echo "   - Build Command: pip install -r requirements.txt"
echo "   - Start Command: gunicorn -w 2 -b 0.0.0.0:\$PORT run:app"
echo "   - Plan: Free"
echo ""
echo "🌐 You will get ONE public URL like:"
echo "   https://genhealth-assessment-api.onrender.com"
echo ""
echo "✅ This URL will have all endpoints working:"
echo "   - GET  /health"
echo "   - GET  /api/orders"
echo "   - POST /api/orders"
echo "   - POST /api/documents/upload"
echo "   - GET  /api/patients"
echo ""
echo "⏱️  Deployment time: ~5 minutes"
echo "🎯 Share this ONE URL with assessment team when ready!"